name: CI/CD for Iris Classifier

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Train model
        run: |
          python src/train.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: iris-model
          path: models/model.pkl

      - name: Build Docker image
        run: |
          docker build -t iris-ml:latest .
